import format from 'date-fns/format';
import { subHours } from 'date-fns';

export const formInit = {
  dateEntered: { label: 'ご記入日', value: format(subHours(new Date(), 9), "yyyy-MM-dd'T'HH:mm:00'Z'") },
  fullname: { label: '【必須】世帯主様お名前', value: '', pageNum: 0, touch: false, valueError: true, errorText: '必須項目です。ご記入をお願いします。' },
  furigana: { label: '【必須】氏名ふりがな', value: '', pageNum: 0, touch: false, valueError: true, errorText: '必須項目です。ご記入をお願いします。' },
  birthday: { label: '【必須】生年月日', value: '', pageNum: 0, touch: false, valueError: true, errorText: '必須項目です。ご記入をお願いします。' },
  postCode: { label: '【必須】郵便番号', value: '', pageNum: 0, touch: false, valueError: true, errorText: '数字で入力してください。例:442-0888' },
  address: { label: '【必須】住所', value: '', pageNum: 0, touch: false, valueError: true, errorText: '必須項目です。ご記入をお願いします。' },
  address2: { label: '住所(建物名)', value: '', pageNum: 0 },
  tel: { label: '【必須】電話番号', value: '', pageNum: 0, touch: false, valueError: true, errorText: '数字で入力してください。例:090-1111-2222' },
  mail: { label: 'メールアドレス', value: '', pageNum: 0, touch: false, valueError: false, errorText: '英数字で入力してください。例:sample@mail.jp' },
  workPlace: { label: 'ご勤務先', pageNum: 0, value: '' },
  holiday: { label: 'ご休日', pageNum: 0, value: '' },
  works: { label: 'ご職業', pageNum: 1, value: '' },
  annualIncome: { label: 'ご年収', value: { min: '', max: '' }, pageNum: 1 },
  visitPurpose: { label: '【必須】ご来場の目的', value: [], pageNum: 1, valueError: true, errorText: '必須項目です。ご記入をお願いします。' },
  vstPrpsOthers: { label: '【必須】その他詳細', value: '', pageNum: 1, valueError: false, errorText: '必須項目です。ご記入をお願いします。' },
  importantPoint: { label: '家づくりで重要視するものはどれですか？(複数回答可)', value: [], pageNum: 2 },
  impPointOthers: { label: 'その他詳細', value: '', pageNum: 2 },
  currentHome: { label: '現在のお住まい', value: '', pageNum: 3 },
  rentPrice: { label: '賃貸 家賃の月額', value: '', pageNum: 3 },
  moveInNum: { label: '【必須】入居予定人数', value: '', pageNum: 3, valueError: true, errorText: '必須項目です。ご記入をお願いします。' },
  moveInForm: { label: '【必須】入居形態', value: '', pageNum: 3, valueError: true, errorText: '必須項目です。ご記入をお願いします。' },
  mvInFormOthers: { label: '【必須】入居形態詳細', value: '', pageNum: 3, valueError: false, errorText: '必須項目です。ご記入をお願いします。' },
  moveInSeason: { label: '入居希望時期', value: '', pageNum: 4 },
  budget: { label: '建物予算', value: { min: '', max: '', pageNum: 4 } },
  ownResources: { label: '自己資金', value: { min: '', max: '' }, pageNum: 4 },
  landExistence: { label: '建築用土地の有無', value: '', pageNum: 4 },
  areaOfLand: { label: '建築用土地の面積(ない場合はご希望面積)', value: '', pageNum: 4 },
  locationOfLand: { label: '建築用土地の所在地(ない場合はご希望地)', value: '', pageNum: 4 },
  siteBrowsing: { label: '当社のホームページをご覧になったことはありますか？', value: '', pageNum: 4 },
  documentRequest: { label: '当社に資料請求をしていただいたことはありますか？', value: '', pageNum: 4 },
  informationSource: { label: '当社の情報を収集する際に利用した情報源をお教えください(複数回答可)', value: [], pageNum: 4 },
  yumePersonInCharge: { label: '夢のおてつだい 担当者の氏名', value: '', pageNum: 4 },
  introducer: { label: 'ご紹介者様のお名前', value: '', pageNum: 4 },
  firstOpportunity: { label: '当社のことを一番最初に知るきっかけとなった情報源', value: '', pageNum: 5 },
  bestOpportunity: { label: '本日のご来場の決め手となった情報源', value: '', pageNum: 5 },
};