import format from 'date-fns/format';

export const formInit ={
  fullname: { label: '名前', value: '' },
  furigana: { label: 'フリガナ', value: '' },
  dateEntered: { label: '記入日', value: format(new Date(), 'yyyy-MM-dd HH:mm') },
  birthday: { label: '誕生日', value: '' },
  postCode: { label: '郵便番号', value: '', valueError: false, errorText: '数字で入力してください。入力例:442-0888' },
  address: { label: '住所', value: '' },
  address2: { label: '住所(建物名)', value: '' },
  tel: { label: 'TEL', value: '', valueError: false, errorText: '数字で入力してください。入力例:090-1111-2222' },
  mail: { label: 'MAIL', value: '', valueError: false, errorText: '英数字で入力してください。入力例:sample@mail.jp' },
  workPlace: { label: 'ご勤務先', value: '' },
  holiday: { label: 'ご休日', value: '' },
  works: { label: 'ご職業', value: '' },
  annualIncome: { label: 'ご年収', value: { min: '', max: '' } },
  visitPurpose: { label: 'ご来場の目的', value: []},
  vstPrpsOthers: { label: 'その他', value: '', },
  importantPoint: { label: '重要視するもの', value: [] },
  impPointOthers: { label: 'その他', value: ''},
  currentHome: { label: '現在のお住まい', value: '' },
  RentPrice: { label: '賃貸の月額', value: '' },
  moveInNum: { label: '入居予定人数', value: '' },
  moveInForm: { label: '入居形態', value: '' },
  mvInFormOthers: { label: '入居形態詳細', value: '' },
  moveInSeason: { label: '入居希望時期', value: '' },
  budget: { label: '建物予算', value: '' },
  ownResources: { label: '自己資金', value: '' },
  landExistence: { label: '土地の有無', value: '' },
  areaOfLand: { label: '土地の面積', value: '' },  
  locationOfLand: { label: '土地の所在', value: '' },  
  siteBrowsing: { label: 'サイトの閲覧', value: '' },
  documentRequest: { label: '資料請求', value: '' },
  infomationSource: { label: '参照情報源', value: '' },
  yumePersonInCharge: { label: '担当者', value: ''},
  introducer: { label: '紹介者', value: ''},
  firstOpportunity: { label: '最初のきっかけ', value: '' },
  bestOpportunity: { label: '一番のきっかけ', value: '' },
};